import {Noto_Serif} from "next/font/google";
import "./globals.css";
import Meta from "@/components/meta";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

import Footer from "@/components/footer";
import {log} from "next/dist/server/typescript/utils";


const merriweather = Noto_Serif({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Meta />
      <body className={ merriweather.className }>{ children }
      </body>
      {/*<Footer />*/ }
    </html>
  );
}
